import path from 'node:path';

import fg from 'fast-glob';
import fs from 'fs-extra';
import prettier from 'prettier';

import { defineArtifacts } from './lib/artifacts.mjs';
import { compileFrameworkFeatures } from './lib/framework-features.mjs';
import { readJsonc } from './lib/jsonc.mjs';
import {
  LEGACY_OAUTH_HELPER_TARGETS,
  MODERN_PATTERN_HINT,
} from './lib/legacy-recipe-patterns.mjs';
import { oauthEntrypointKind } from './lib/oauth-entrypoint.mjs';

const STYLE_HEADER = `/**
 * GENERATED by scripts/build-artifacts.mjs -- do not edit.
 *
 * Shared cookbook styling: design tokens synced from glean-developer-site plus
 * the primitives built on them. Edit styles/cookbook.css at the repo root (or
 * re-run scripts/sync-brand-tokens.mjs for tokens) and rebuild.
 */
`;

async function recipeFiles(repoRoot) {
  return fg('recipes/*/recipe.json', { cwd: repoRoot, absolute: true });
}

function executionTarget(recipe, execution) {
  const assets = recipe.codeAssets ?? [];
  if (assets.length === 1) return assets[0].repoPath;
  const setup = execution.auth.map((auth) => auth.setupCommand ?? '').join(' ');
  return assets.find((asset) => setup.includes(path.basename(asset.repoPath)))
    ?.repoPath;
}

function oauthExecutionTargets(recipe) {
  return [
    ...(recipe.execution
      ? [
          {
            execution: recipe.execution,
            target: executionTarget(recipe, recipe.execution),
          },
        ]
      : []),
    ...(recipe.codeAssets ?? []).flatMap((asset) =>
      asset.execution
        ? [{ execution: asset.execution, target: asset.repoPath }]
        : [],
    ),
  ]
    .filter(({ execution }) =>
      execution.auth.some((auth) => auth.kind === 'oauth-with-token-fallback'),
    )
    .map(({ target }) => target);
}

// The copied helper generated from scripts/recipe-auth.mjs is legacy. This plan
// only keeps the existing copies on LEGACY_OAUTH_HELPER_TARGETS in sync; it
// never adopts a new target by glob or by declared auth kind.
export async function legacyOAuthHelperTargets(
  { repoRoot },
  allowlist = LEGACY_OAUTH_HELPER_TARGETS,
) {
  const targets = Object.keys(allowlist).sort();
  const errors = [];
  const shipped = await fg(
    [
      'recipes/**/scripts/glean-auth.mjs',
      'plugin/shared/cookbook/scripts/glean-auth.mjs',
    ],
    { cwd: repoRoot, ignore: ['**/node_modules/**'] },
  );
  for (const file of shipped.sort()) {
    const target = path.posix.dirname(path.posix.dirname(file));
    if (!Object.hasOwn(allowlist, target)) {
      errors.push(
        `${file} is the legacy copied OAuth helper, and ${target} is not on LEGACY_OAUTH_HELPER_TARGETS. Delete it. ${MODERN_PATTERN_HINT}`,
      );
    }
  }
  for (const target of targets) {
    const helper = path.join(repoRoot, target, 'scripts', 'glean-auth.mjs');
    if (!(await fs.pathExists(helper))) {
      errors.push(
        `${target} no longer ships scripts/glean-auth.mjs; remove it from LEGACY_OAUTH_HELPER_TARGETS in scripts/lib/legacy-recipe-patterns.mjs.`,
      );
    }
  }
  for (const file of await recipeFiles(repoRoot)) {
    const recipe = readJsonc(file);
    for (const target of oauthExecutionTargets(recipe)) {
      if (!target) {
        errors.push(
          `${recipe.id}: cannot resolve the scaffold that owns its OAuth execution contract`,
        );
      } else if (
        !oauthEntrypointKind(repoRoot, target, { helperTargets: allowlist })
      ) {
        errors.push(
          `${recipe.id}: ${target} declares OAuth, but its \`login\` script is not \`glean-auth login\` from a pinned @gleanwork/auth and it is not an allowlisted legacy target. ${MODERN_PATTERN_HINT}`,
        );
      }
    }
  }
  if (errors.length > 0) {
    throw new Error(`OAuth artifact plan failures:\n- ${errors.join('\n- ')}`);
  }
  return targets.map((target) => `${target}/scripts/glean-auth.mjs`);
}

async function uiScaffolds({ repoRoot }) {
  const entrypoints = await fg(
    [
      'recipes/*/index.html',
      'recipes/*/*/index.html',
      'recipes/**/public/index.html',
    ],
    { cwd: repoRoot },
  );
  const roots = new Set();
  for (const entrypoint of entrypoints) {
    if (entrypoint.includes('/dist/') || entrypoint.includes('/shared/')) {
      continue;
    }
    const root = entrypoint.endsWith('/public/index.html')
      ? path.dirname(path.dirname(entrypoint))
      : path.dirname(entrypoint);
    if (await fs.pathExists(path.join(repoRoot, root, 'package.json'))) {
      roots.add(root);
    }
  }
  return [...roots].sort();
}

async function nodeServerScaffolds({ repoRoot }) {
  return (await fg('recipes/**/server.ts', { cwd: repoRoot }))
    .filter((file) => !file.includes('/node_modules/'))
    .map((file) => path.dirname(file));
}

async function customer360UiTargets({ repoRoot }) {
  const recipe = readJsonc(
    path.join(repoRoot, 'recipes/customer-360/recipe.json'),
  );
  return recipe.codeAssets.map(
    (asset) => `${asset.repoPath}/public/index.html`,
  );
}

async function cookbookStyles({ repoRoot }) {
  const sources = await Promise.all(
    ['styles/tokens.css', 'styles/cookbook.css'].map((file) =>
      fs.readFile(path.join(repoRoot, file), 'utf8'),
    ),
  );
  const target = path.join(
    repoRoot,
    'recipes/company-answers/chat-api/public/glean-cookbook.css',
  );
  return prettier.format(`${STYLE_HEADER}\n${sources.join('\n')}`, {
    ...(await prettier.resolveConfig(target)),
    filepath: target,
  });
}

const { artifactDefinitions: frameworkFeatureArtifacts } =
  await compileFrameworkFeatures({
    repoRoot: path.resolve(import.meta.dirname, '..'),
  });

export default defineArtifacts([
  {
    id: 'recipe-auth',
    content: ({ repoRoot }) =>
      fs.readFile(path.join(repoRoot, 'scripts/recipe-auth.mjs')),
    targets: (context) => legacyOAuthHelperTargets(context),
    mode: 0o755,
  },
  {
    id: 'backend-resolver',
    content: ({ repoRoot }) =>
      fs.readFile(
        path.join(
          repoRoot,
          'plugin/shared/cookbook/scripts/resolve-backend.mjs',
        ),
      ),
    targets: async () => [
      'recipes/gong-call-follow-up-n8n/scripts/resolve-backend.mjs',
    ],
    mode: 0o755,
  },
  {
    id: 'cookbook-styles',
    content: cookbookStyles,
    targets: async (context) =>
      (await uiScaffolds(context)).map(
        (root) => `${root}/public/glean-cookbook.css`,
      ),
  },
  {
    id: 'cookbook-logo',
    content: ({ repoRoot }) =>
      fs.readFile(path.join(repoRoot, 'brand/glean-logomark.svg')),
    targets: async (context) =>
      (await uiScaffolds(context)).map(
        (root) => `${root}/public/glean-logomark.svg`,
      ),
  },
  {
    id: 'customer-360-ui',
    content: ({ repoRoot }) =>
      fs.readFile(
        path.join(repoRoot, 'recipes/customer-360/shared/index.html'),
      ),
    targets: customer360UiTargets,
  },
  {
    id: 'local-server-runtime',
    content: ({ repoRoot }) =>
      fs.readFile(path.join(repoRoot, 'runtime/local-server.ts')),
    targets: async (context) =>
      (await nodeServerScaffolds(context)).map(
        (root) => `${root}/lib/cookbook-server.ts`,
      ),
  },
  ...frameworkFeatureArtifacts,
]);
