import path from 'node:path';

import fg from 'fast-glob';
import fs from 'fs-extra';
import prettier from 'prettier';

import { defineArtifacts } from './lib/artifacts.mjs';

const STYLE_HEADER = `/**
 * GENERATED by scripts/build-artifacts.mjs -- do not edit.
 *
 * Shared cookbook styling: design tokens synced from glean-developer-site plus
 * the primitives built on them. Edit styles/cookbook.css at the repo root (or
 * re-run scripts/sync-brand-tokens.mjs for tokens) and rebuild.
 */
`;

async function recipeFiles(repoRoot) {
  return fg('recipes/*/recipe.json', { cwd: repoRoot, absolute: true });
}

function executionTarget(recipe, execution) {
  const assets = recipe.codeAssets ?? [];
  if (assets.length === 1) return assets[0].repoPath;
  const setup = execution.auth.map((auth) => auth.setupCommand ?? '').join(' ');
  return assets.find((asset) => setup.includes(path.basename(asset.repoPath)))
    ?.repoPath;
}

async function oauthScaffolds({ repoRoot }) {
  const targets = new Set(['plugin/plugins/cookbook']);
  for (const file of await recipeFiles(repoRoot)) {
    const recipe = await fs.readJson(file);
    const contracts = [
      ...(recipe.execution
        ? [
            {
              execution: recipe.execution,
              target: executionTarget(recipe, recipe.execution),
            },
          ]
        : []),
      ...(recipe.codeAssets ?? []).flatMap((asset) =>
        asset.execution
          ? [{ execution: asset.execution, target: asset.repoPath }]
          : [],
      ),
    ];
    for (const { execution, target } of contracts) {
      if (
        !execution.auth.some(
          (auth) => auth.kind === 'oauth-with-token-fallback',
        )
      ) {
        continue;
      }
      if (!target) {
        throw new Error(
          `${recipe.id}: cannot resolve the scaffold that owns its OAuth execution contract`,
        );
      }
      targets.add(target);
    }
  }
  return [...targets].map((target) => `${target}/scripts/glean-auth.mjs`);
}

async function uiScaffolds({ repoRoot }) {
  const entrypoints = await fg(
    [
      'recipes/*/index.html',
      'recipes/*/*/index.html',
      'recipes/**/public/index.html',
    ],
    { cwd: repoRoot },
  );
  const roots = new Set();
  for (const entrypoint of entrypoints) {
    if (entrypoint.includes('/dist/') || entrypoint.includes('/shared/')) {
      continue;
    }
    const root = entrypoint.endsWith('/public/index.html')
      ? path.dirname(path.dirname(entrypoint))
      : path.dirname(entrypoint);
    if (await fs.pathExists(path.join(repoRoot, root, 'package.json'))) {
      roots.add(root);
    }
  }
  return [...roots].sort();
}

async function nodeServerScaffolds({ repoRoot }) {
  return (await fg('recipes/**/server.ts', { cwd: repoRoot }))
    .filter((file) => !file.includes('/node_modules/'))
    .map((file) => path.dirname(file));
}

async function customer360UiTargets({ repoRoot }) {
  const recipe = await fs.readJson(
    path.join(repoRoot, 'recipes/customer-360/recipe.json'),
  );
  return recipe.codeAssets.map(
    (asset) => `${asset.repoPath}/public/index.html`,
  );
}

async function cookbookStyles({ repoRoot }) {
  const sources = await Promise.all(
    ['styles/tokens.css', 'styles/cookbook.css'].map((file) =>
      fs.readFile(path.join(repoRoot, file), 'utf8'),
    ),
  );
  const target = path.join(
    repoRoot,
    'recipes/company-answers/chat-api/public/glean-cookbook.css',
  );
  return prettier.format(`${STYLE_HEADER}\n${sources.join('\n')}`, {
    ...(await prettier.resolveConfig(target)),
    filepath: target,
  });
}

export default defineArtifacts([
  {
    id: 'recipe-auth',
    content: ({ repoRoot }) =>
      fs.readFile(path.join(repoRoot, 'scripts/recipe-auth.mjs')),
    targets: oauthScaffolds,
    mode: 0o755,
  },
  {
    id: 'cookbook-styles',
    content: cookbookStyles,
    targets: async (context) =>
      (await uiScaffolds(context)).map(
        (root) => `${root}/public/glean-cookbook.css`,
      ),
  },
  {
    id: 'cookbook-logo',
    content: ({ repoRoot }) =>
      fs.readFile(path.join(repoRoot, 'brand/glean-logomark.svg')),
    targets: async (context) =>
      (await uiScaffolds(context)).map(
        (root) => `${root}/public/glean-logomark.svg`,
      ),
  },
  {
    id: 'customer-360-ui',
    content: ({ repoRoot }) =>
      fs.readFile(
        path.join(repoRoot, 'recipes/customer-360/shared/index.html'),
      ),
    targets: customer360UiTargets,
  },
  {
    id: 'local-server-runtime',
    content: ({ repoRoot }) =>
      fs.readFile(path.join(repoRoot, 'runtime/local-server.ts')),
    targets: async (context) =>
      (await nodeServerScaffolds(context)).map(
        (root) => `${root}/lib/cookbook-server.ts`,
      ),
  },
]);
