#!/usr/bin/env node
/**
 * Distributes the shared stylesheet into every recipe UI.
 *
 * Recipes are scaffolded one directory at a time with `tiged`, so a shared file
 * at the repo root never reaches a scaffolded recipe -- and most recipes have no
 * bundler to import one. Each therefore gets a committed copy, generated from
 * styles/, the same way registry.json and the plugin's build/ output work.
 *
 *   node scripts/build-styles.mjs [--check]
 *
 * --check exits non-zero when a copy is stale instead of writing, for CI.
 */
import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';

const repoRoot = path.resolve(import.meta.dirname, '..');
const check = process.argv.includes('--check');

const SOURCES = ['styles/tokens.css', 'styles/cookbook.css'];
const STYLESHEET = 'glean-cookbook.css';
const LOGO = 'glean-logomark.svg';

/**
 * Every recipe that renders a UI. Both kinds of recipe serve public/ at the
 * root -- Express via static(), Vite via its default publicDir -- so one
 * destination and one <link href="/glean-cookbook.css"> works for all of them.
 */
const RECIPE_UIS = [
  'recipes/company-answers/chat-api',
  'recipes/company-answers/web-sdk',
  'recipes/customer-360/platform-agents',
  'recipes/customer-360/platform-search-chat',
  'recipes/incident-copilot',
  'recipes/onboarding-hub/platform-chat',
  'recipes/onboarding-hub/web-sdk',
  'recipes/rfp-responder',
];

const HEADER = `/**
 * GENERATED by scripts/build-styles.mjs -- do not edit.
 *
 * Shared cookbook styling: design tokens synced from glean-developer-site plus
 * the primitives built on them. Edit styles/cookbook.css at the repo root (or
 * re-run scripts/sync-brand-tokens.mjs for tokens) and rebuild.
 */
`;

function readSource(rel) {
  const file = path.join(repoRoot, rel);
  if (!fs.existsSync(file)) {
    console.error(
      `\u2717 Missing ${rel}.` +
        (rel.includes('tokens')
          ? ' Generate it with: npm run sync:tokens'
          : ''),
    );
    process.exit(1);
  }
  return fs.readFileSync(file, 'utf8');
}

/**
 * Tokens first: they carry the @import font rules, and CSS requires @import to
 * precede every other rule in a stylesheet.
 *
 * Formatted through prettier, like build-registry.mjs does for registry.json,
 * so the generated copies pass format:check alongside authored files.
 */
const target = path.join(repoRoot, RECIPE_UIS[0], 'public', STYLESHEET);
const stylesheet = await prettier.format(
  HEADER + '\n' + SOURCES.map(readSource).join('\n'),
  { ...(await prettier.resolveConfig(target)), filepath: target },
);
const logo = fs.readFileSync(path.join(repoRoot, 'brand', LOGO));

let stale = 0;
let written = 0;

for (const recipe of RECIPE_UIS) {
  const dir = path.join(repoRoot, recipe, 'public');
  const targets = [
    { file: path.join(dir, STYLESHEET), next: Buffer.from(stylesheet) },
    { file: path.join(dir, LOGO), next: logo },
  ];

  for (const { file, next } of targets) {
    const rel = path.relative(repoRoot, file);
    const current = fs.existsSync(file) ? fs.readFileSync(file) : null;
    if (current !== null && current.equals(next)) continue;

    stale += 1;
    if (check) {
      console.error(
        `\u2717 ${rel} is ${current === null ? 'missing' : 'stale'}`,
      );
      continue;
    }
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(file, next);
    console.log(`\u2192 ${rel}`);
    written += 1;
  }
}

if (check) {
  if (stale > 0) {
    console.error(
      `\n${stale} generated file(s) stale across ${RECIPE_UIS.length} recipe UIs. Run: npm run build:styles`,
    );
    process.exit(1);
  }
  console.log(
    `\u2713 ${RECIPE_UIS.length} recipe UIs up to date (${STYLESHEET}, ${LOGO})`,
  );
} else {
  console.log(
    written === 0
      ? `\u2713 already up to date across ${RECIPE_UIS.length} recipe UIs`
      : `Wrote ${written} file(s) across ${RECIPE_UIS.length} recipe UIs`,
  );
}
